### ISSUE TITLE
Unable to access Terraform Cloud due to "invalid certificate: UnknownIssuer"

### ISSUE THREAD

**Issue by RyanMarkoff-eaton** [06chaynes/tfc-toolset#19]
Hey Christian!

I was trying out your tfct cli and I'm running into some TLS errors due to Zscaler intercepting all of the traffic and breaking TLS. I'm not familiar with rust, but I was able to workaround this same problem using python and installing `pip-system-certs`. 

From what I have found online, this could be fixed with using `rustls-native-certs` instead of `webpki-roots` because it will read my local certificate store instead of Mozilla's. I did try creating an environment variable `RUSTUP_USE_CURL=1` but that didn't change the error below.

```
[2024-04-17T15:17:07Z INFO  tfct::cli::command::workspace::list] Retrieving Workspaces.
[2024-04-17T15:17:07Z INFO  tfc_toolset::workspace] Retrieving the initial list of workspaces.
[2024-04-17T15:17:07Z WARN  rustls::session] Sending fatal alert BadCertificate
[2024-04-17T15:17:07Z WARN  rustls::session] Sending fatal alert BadCertificate
Error:   x An error occured while creating a new object: invalid certificate: UnknownIssuer
```

**Comment by 06chaynes** [comment]
Nice, good to know. I'm cool with making that change, I should be able to tweak and test that soon!

**Comment by 06chaynes** [comment]
@RyanMarkoff-eaton I have the new version publishing new using native tls, should resolve this I believe but lmk if that turns out not to be the case.

**Comment by RyanMarkoff-eaton** [comment]
> @RyanMarkoff-eaton I have the new version publishing new using native tls, should resolve this I believe but lmk if that turns out not to be the case.

Awesome! I'll give it try

**Comment by RyanMarkoff-eaton** [comment]
> @RyanMarkoff-eaton I have the new version publishing new using native tls, should resolve this I believe but lmk if that turns out not to be the case.

That fixed it, thank you!!
